### ISSUE TITLE
error opening oneapi_asp editor IP in quartus 24.1pro

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/oneapi-asp#162]
i was building oneapi-asp for OFS release ofs-2024.2-1 (FIM tag  ofs-2024.2-1). According to docs

https://ofs.github.io/ofs-2024.2-1/hw/common/user_guides/oneapi_asp/ug_oneapi_asp/#23-prerequisites

For FIM ofs-2024.2-1, oneapi-asp tag  ofs-2024.2-2 instead of ofs-2024.2-1 (does the old tag ofs-2024.2-1 has any problem  ?)

In this new  ofs-2024.2-2, there is new oneapi_asp editor IP , when i open this quartus 24.1pro I got following error

![Screenshot 2024-11-27 183410](https://github.com/user-attachments/assets/6da9f263-5157-46d9-8d28-c2b7a11faff6)

![image](https://github.com/user-attachments/assets/1a67bf8f-6d48-4e9a-bf63-5d86853f29ce)

i have installed the quartus patches required by OFS

![image](https://github.com/user-attachments/assets/d0634fb0-36dd-48b4-8f1a-d92b0329c906)

**Comment by aktole** [comment]
Hi, 

This is due to a known issue in the oneapi_asp_editor_hw.tcl script ([line 1054](https://github.com/OFS/oneapi-asp/blob/76ba584312fcc1e08c76407f26b2034d315fd53e/oneapi_asp_editor/oneapi_asp_editor_hw.tcl#L1054)). Please refer to issue ID 14023830020 in the known issues table and its suggested workaround in the release notes here: https://github.com/OFS/oneapi-asp/releases/tag/ofs-2024.2-2.

Thank you.
